function [hMenu, hMenuItem] = addMenu(hFig_main)

%% tps
hMenu.snake = uimenu('Parent',                 hFig_main,...
                    'HandleVisibility',      'off', ...
                    'Label',                     'Snake');
                                            
hMenuItem.LoadImages  =   uimenu('Parent',               hMenu.snake,...
                                'Label',                'Load Images',...
                                    'Checked',           'off',...
                                    'Enable',               'on', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_LoadImages_Callback);
                            
hMenuItem.FreeHand  =   uimenu('Parent',               hMenu.snake,...
                                'Label',                'Free Hand',...
                                    'Checked',           'off',...
                                    'Enable',               'off', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_FreeHand_Callback);
                            
hMenuItem.Snake  =   uimenu('Parent',               hMenu.snake,...
                                'Label',                'Slither',...
                                    'Checked',           'off',...
                                    'Enable',               'off', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_Snake1_Callback);
                            
hMenuItem.SaveSnakes  =   uimenu('Parent',               hMenu.snake,...
                                'Label',                'Save Snakes',...
                                    'Checked',           'off',...
                                    'Enable',               'off', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_SaveSnakes_Callback);
                            
hMenu.data = uimenu('Parent',                 hFig_main,...
                    'HandleVisibility',      'off', ...
                    'Label',                     'Data');
                                            
hMenuItem.Point  =   uimenu('Parent',               hMenu.data,...
                                'Label',                'Point on Diaphragm',...
                                    'Checked',           'off',...
                                    'Enable',               'on', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_Point_Callback);
                            
hMenuItem.PlotPoint  =   uimenu('Parent',               hMenu.data,...
                                'Label',                'Points Plot',...
                                    'Checked',           'off',...
                                    'Enable',               'on', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_PlotPoint_Callback);
                            
hMenuItem.SavePoints  =   uimenu('Parent',               hMenu.data,...
                                'Label',                'Save Points',...
                                    'Checked',           'off',...
                                    'Enable',               'off', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_SavePoints_Callback);

