function [hMenu, hMenuItem] = addMenu(hFig_main)

%% snake
hMenu.snake = uimenu('Parent',                 hFig_main,...
                    'HandleVisibility',      'off', ...
                    'Label',                     'Snake');
                                            
hMenuItem.LoadImages  =   uimenu('Parent',               hMenu.snake,...
                                'Label',                'Load Images',...
                                    'Checked',           'off',...
                                    'Enable',               'on', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_LoadImages_Callback);
                            
hMenuItem.FreeHand  =   uimenu('Parent',               hMenu.snake,...
                                'Label',                'Free Hand',...
                                    'Checked',           'off',...
                                    'Enable',               'off', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_FreeHand_Callback);
                            
hMenuItem.Snake  =   uimenu('Parent',               hMenu.snake,...
                                'Label',                'Slither',...
                                    'Checked',           'off',...
                                    'Enable',               'off', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_Snake1_Callback);
                            
hMenuItem.SaveSnakes  =   uimenu('Parent',               hMenu.snake,...
                                'Label',                'Save Snakes',...
                                    'Checked',           'off',...
                                    'Enable',               'off', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_SaveSnakes_Callback);

%% Point                            
hMenu.Point = uimenu('Parent',                 hFig_main,...
                    'HandleVisibility',      'off', ...
                    'Label',                     'Points');
                                            
hMenuItem.PointPreProcess  =   uimenu('Parent',               hMenu.Point,...
                                'Label',                'preProcess',...
                                    'Checked',           'off',...
                                    'Enable',               'on', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_PointPreProcess_Callback);

hMenuItem.PointParam  =   uimenu('Parent',               hMenu.Point,...
                                'Label',                'On/Off - Neighbour Points',...
                                    'Checked',           'off',...
                                    'Enable',               'on', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_PointParam_Callback);

hMenuItem.Point  =   uimenu('Parent',               hMenu.Point,...
                                'Label',                'Points on Diaphragm',...
                                    'Checked',           'off',...
                                    'Enable',               'on', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_Point_Callback);
                            
% hMenuItem.PlotPoint  =   uimenu('Parent',               hMenu.Point,...
%                                 'Label',                'Points Plot',...
%                                     'Checked',           'off',...
%                                     'Enable',               'on', ...
%                                     'Separator',          'on', ...
%                                 'HandleVisibility', 'callback', ...
%                                 'Callback',            @hMenuItem_PlotPoint_Callback);
                            
hMenuItem.DeletePoint  =   uimenu('Parent',               hMenu.Point,...
                                'Label',                'On/Off Delete Contour',...
                                    'Checked',           'off',...
                                    'Enable',               'on', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_DeletePoint_Callback);

hMenuItem.SavePoints  =   uimenu('Parent',               hMenu.Point,...
                                'Label',                'Save Points',...
                                    'Checked',           'off',...
                                    'Enable',               'off', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_SavePoints_Callback);
                            
%% Point                            
hMenu.Tumor = uimenu('Parent',                 hFig_main,...
                    'HandleVisibility',      'off', ...
                    'Label',                     'Tumor');
                                            
hMenuItem.Tumor.bwSum  =   uimenu('Parent',               hMenu.Tumor,...
                                'Label',                'Tumor Overlay',...
                                    'Checked',           'off',...
                                    'Enable',               'off', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_Tumor_bwSum_Callback);
                            
hMenuItem.Tumor.TrackContour  =   uimenu('Parent',               hMenu.Tumor,...
                                'Label',                'Contour Overlay',...
                                    'Checked',           'off',...
                                    'Enable',               'off', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_Tumor_TrackContour_Callback);
                            
hMenuItem.Tumor.Points  =   uimenu('Parent',               hMenu.Tumor,...
                                'Label',                'Points on Diaphragm',...
                                    'Checked',           'off',...
                                    'Enable',               'off', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_Tumor_Points_Callback);

hMenuItem.Tumor.Profile  =   uimenu('Parent',               hMenu.Tumor,...
                                'Label',                'Profile',...
                                    'Checked',           'off',...
                                    'Enable',               'off', ...
                                    'Separator',          'on', ...
                                'HandleVisibility', 'callback', ...
                                'Callback',            @hMenuItem_Tumor_Profile_Callback);
