function [hPB] = addPanel_Slither(parent)

wCell = 0.5;
hCell = 1;
xP(1) = 0;
xP(2) = xP(1)+wCell;
yP = [0 0];


% all buttons
for iC = 1:2
    hPN(iC) = uipanel('parent', parent,...
                            'Unit', 'Normalized',...
                            'Position', [xP(iC) yP(iC) wCell hCell],...
                            'Units',                     'normalized', ...
                            'visible',                      'on', ...
                            'ForegroundColor',       'k',...
                            'BackgroundColor',       'k', ...
                            'HighlightColor',          'w',...
                            'ShadowColor',            'k');
end


hPB.Start = uicontrol('Parent', hPN(1), ...
                                'Style', 'pushbutton', ...
                                'Units',  'normalized', ...
                                'Position', [0. 0. 1, 1], ...
                                'FontSize', 16, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.2,...
                                'ForegroundColor', 'g',...
                                'String', 'Start', ...
                                'Visible', 'on',...
                                'Callback', @hPushButton_Slither2_Start_Callback);

                            
hPB.Stop = uicontrol('Parent', hPN(2), ...
                                'Style', 'pushbutton', ...
                                'Units',  'normalized', ...
                                'Position', [0. 0. 1, 1], ...
                                'FontSize', 16, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', [1 1 1]*0.2,...
                                'ForegroundColor', 'r',...
                                'String', 'Stop', ...
                                'Visible', 'on',...
                                'UserData', false,...
                                'Callback', @hPushButton_Slither_Stop_Callback);                            