function [hPU] = fun_myTablePopup(parent, txt, cellWidthRatio)

nR = length(txt.FirstColumn);

wCell = cellWidthRatio/sum(cellWidthRatio);
hCell = 1/nR;
junk = cumsum(wCell);
xP = [0 junk(1:end-1)];
yP = hCell*(nR-1):-hCell:0;

% all cells
for iR = 1:nR
    for iC = 1:2
        hPN(iR, iC) = uipanel('parent', parent,...
                                'Unit', 'Normalized',...
                                'Position', [xP(iC) yP(iR) wCell(iC) hCell],...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'w',...
                                'ShadowColor',            'k');
    end
end

% first column
for iR = 1:nR
    hText.FirsColumn(iR) = uicontrol('parent', hPN(iR, 1), ...
                                'Style', 'text',...
                                'String', txt.FirstColumn{iR},...
                                'Unit', 'Normalized',...
                                'Position', [0 0 1 1], ...
                                'FontSize', 12, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', 'k',...
                                'ForegroundColor', 'w',...
                                'Visible', 'on');
end

% data
for iR = 1:nR
    hPU(iR) = uicontrol('parent', hPN(iR, 2), ...
                            'Style', 'popupmenu',...
                            'Unit', 'Normalized',...
                            'Position', [0 0 1 1],...
                            'FontSize', 12, ...
                            'FontWeight', 'bold', ...
                            'BackgroundColor', 'k',...
                            'ForegroundColor', 'c',...
                            'String', txt.DataStr{iR}, ...
                            'Visible', 'on');

end
